USE [tst33]
GO

/****** Object:  Table [dbo].[gruppa]    Script Date: 21.02.2024 11:54:17 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[gruppa](
	[gr_id] [int] IDENTITY(1,1) NOT NULL,
	[naim] [varchar](50) NOT NULL,
	[spec] [varchar](50) NOT NULL,
 CONSTRAINT [PK_gruppa] PRIMARY KEY CLUSTERED 
(
	[gr_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

