unit TestTestmain;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, Variants, ExtCtrls, Messages, Classes, SysUtils, main, Windows, StdCtrls, 
  Forms, Dialogs, Testmain, Graphics, Controls;
type
  // Test methods for class TestTForm1
  
  TestTestTForm1 = class(TTestCase)
  strict private
    FestTForm1: TestTForm1;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestSetUp;
    procedure TestTearDown;
    procedure TestTestto_summ;
  end;

implementation

procedure TestTestTForm1.SetUp;
begin
  FestTForm1 := TestTForm1.Create(NIL);
end;

procedure TestTestTForm1.TearDown;
begin
  FestTForm1.Free;
  FestTForm1 := nil;
end;

procedure TestTestTForm1.TestSetUp;
begin
  FestTForm1.SetUp;
  // TODO: Validate method results
    Check(MaxInt>=ReturnValue);
end;

procedure TestTestTForm1.TestTearDown;
begin
  FestTForm1.TearDown;
  // TODO: Validate method results
end;

procedure TestTestTForm1.TestTestto_summ;
begin
  FestTForm1.Testto_summ;
  // TODO: Validate method results
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTestTForm1.Suite);
end.

