USE [master]
GO

/****** Object:  Database [hotel]    Script Date: 15.12.2020 20:55:49 ******/
CREATE DATABASE [hotel]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'hotel', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\hotel.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'hotel_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\hotel_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [hotel] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [hotel].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [hotel] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [hotel] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [hotel] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [hotel] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [hotel] SET ARITHABORT OFF 
GO

ALTER DATABASE [hotel] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [hotel] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [hotel] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [hotel] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [hotel] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [hotel] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [hotel] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [hotel] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [hotel] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [hotel] SET  DISABLE_BROKER 
GO

ALTER DATABASE [hotel] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [hotel] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [hotel] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [hotel] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [hotel] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [hotel] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [hotel] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [hotel] SET RECOVERY FULL 
GO

ALTER DATABASE [hotel] SET  MULTI_USER 
GO

ALTER DATABASE [hotel] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [hotel] SET DB_CHAINING OFF 
GO

ALTER DATABASE [hotel] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [hotel] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [hotel] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [hotel] SET QUERY_STORE = OFF
GO

USE [hotel]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [hotel] SET  READ_WRITE 
GO

