USE [library_r]
GO

/****** Object:  StoredProcedure [dbo].[INS_BOOK]    Script Date: 01.04.2025 20:04:51 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROC [dbo].[INS_BOOK]

@NAME_B VARCHAR(150),
@m_SOURCE VARCHAR(70),
@DATE_P DATE, 
@m_COUNT INT,
@PRICE DECIMAL(5,2), 
@ID_GENRE INT,
@ID_AUTHOR INT,
 @PUBLISHER VARCHAR(50),
 @NAMBER_PAGES INT,
 @YEAR_PUB INT,
@Id int OUT
AS 
begin
INSERT INTO Book(NAME_B,m_SOURCE, DATE_P,m_COUNT,PRICE,ID_GENRE,ID_AUTHOR,PUBLISHER,Number_of_Pages,Year_of_Pub)
VALUES(@NAME_B,@m_SOURCE,@DATE_P,@m_COUNT,@PRICE,@ID_GENRE,@ID_AUTHOR,@PUBLISHER,@NAMBER_PAGES,@YEAR_PUB)
SET @Id = SCOPE_IDENTITY()
end
GO

