USE [library_r]
GO

/****** Object:  StoredProcedure [dbo].[INS_BOOK_normal]    Script Date: 04.04.2025 11:55:07 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[INS_BOOK_normal]

@NAME_B VARCHAR(150),
@m_SOURCE VARCHAR(70),
@DATE_P DATE, 
@m_COUNT INT,
@PRICE DECIMAL(5,2), 
@ID_GENRE INT,
@ID_AUTHOR INT,
 @PUBLISHER VARCHAR(50),
 @NAMBER_PAGES INT,
 @YEAR_PUB INT
AS 
begin
INSERT INTO Book(NAME_B,m_SOURCE, DATE_P,m_COUNT,PRICE,ID_GENRE,ID_AUTHOR,PUBLISHER,Number_of_Pages,Year_of_Pub)
VALUES(@NAME_B,@m_SOURCE,@DATE_P,@m_COUNT,@PRICE,@ID_GENRE,@ID_AUTHOR,@PUBLISHER,@NAMBER_PAGES,@YEAR_PUB)
end


GO

