USE [library]
GO

/****** Object:  Table [dbo].[Doc]    Script Date: 28.03.2025 9:29:34 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Doc](
	[ID_Doc] [int] IDENTITY(1,1) NOT NULL,
	[ID_Book] [int] NOT NULL,
	[m_Status] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_Doc] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Doc]  WITH CHECK ADD  CONSTRAINT [FK_Doc_ Book] FOREIGN KEY([ID_Book])
REFERENCES [dbo].[ Book] ([ID_Book])
GO

ALTER TABLE [dbo].[Doc] CHECK CONSTRAINT [FK_Doc_ Book]
GO

