USE [library]
GO

/****** Object:  Table [dbo].[Genre]    Script Date: 28.03.2025 9:29:58 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Genre](
	[ID_Genre] [int] IDENTITY(1,1) NOT NULL,
	[Name_G] [varchar](70) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_Genre] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

